### ISSUE TITLE
Allow to configure Weave mtu

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#1015]
**What would you like to be added**:

Option to define custom MTU value for Weave network provider.

**Why is this needed**:

Sometimes using "jumbo frames" makes big differene.

**Example cluster.yml**:

```yaml
network:
  provider: weave
  weave:
    mtu: 9000
```
