### ISSUE TITLE
Upgrade Pharos to 2.2.0+oss fails

### ISSUE THREAD

**Issue by johnraz** [kontena/pharos-cluster#1057]
**What happened**:
Upgrading from 2.1.5+oss to 2.2.0+oss fails with the error below:

```
==> Upgrade master @ nuc
    [nuc] Upgrading control plane to v1.13.2 ...
    got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 1: sudo /usr/local/bin/pharos-kubeadm-1.13.2 upgrade apply 1.13.2 -y --ignore-preflight-errors=all --allow-experimental-upgrades --config /tmp/kubeadm.cfg.76e5a97ebaac1ef3cb9872140a93901f
[preflight] Running pre-flight checks.
W0211 00:16:39.171244    7793 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubelet.config.k8s.io", Version:"v1beta1", Kind:"KubeletConfiguration"}: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field KubeletConfiguration.readOnlyPort of type int32
v1beta1.KubeletConfiguration.ReadOnlyPort: readUint32: unexpected character: �, error found in #10 byte of ...|nlyPort":"10255","se|..., bigger context ...|e}},"kind":"KubeletConfiguration","readOnlyPort":"10255","serverTLSBootstrap":true,"staticPodPath":"|...
    retrying after 2 seconds ...
    [nuc] Upgrading control plane to v1.13.2 ...
    got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 1: sudo /usr/local/bin/pharos-kubeadm-1.13.2 upgrade apply 1.13.2 -y --ignore-preflight-errors=all --allow-experimental-upgrades --config /tmp/kubeadm.cfg.892faa07ffe8c1771d2b98298fc087b3
```
I also tried with 2.2.0 pro for the sake of experiment and got the same error.@

**What you expected to happen**:
I expected the cluster upgrade to pass without error.

**How to reproduce it (as minimally and precisely as possible)**:
I guess installing a 2.1.5+oss and upgrading to 2.2.0+oss should trigger the bug.

**Anything else we need to know?**:

**Environment**:
- Pharos version (use `pharos --version`): 2.2.0 and 2.2.0+oss
- Cloud provider or hardware configuration: local server, intel nuc.
- OS (e.g. from /etc/os-release; both for the client and for the used nodes):
client: MacOS X Mojave
server: Ubuntu 16.04.5

**cluster.yml:**

```
hosts:
  - address: xxxxxxxx
    private_interface: eth0
    user: xxxxx
    ssh_key_path: xxxxxxx
    role: master
    container_runtime: docker
    taints: []
network:
  service_cidr: xxxxxxxx/16
  pod_network_cidr: xxxxxxxx/16
addons:
  ingress-nginx:
    enabled: true
  cert-manager:
    enabled: true
    issuer:
      name: letsencrypt-staging
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      email: xxxxxxx
kubelet:
  read_only_port: true
```

Let me know if you need more details.
