### ISSUE TITLE
Allow to enable feature gates

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#1068]
**What would you like to be added**:

Possibility to enable feature gates via `cluster.yml`.

**Example cluster.yml**:

```yaml
api:
  feature_gates: {}
kubelet:
  feature_gates: {}
```
