### ISSUE TITLE
Bastion opens an extra ssh connection

### ISSUE THREAD

**Issue by kke** [kontena/pharos-cluster#1072]
When using a bastion host, unused extra ssh connections will be opened when creating a kube client. This is because:

```ruby
bastion.host.ssh.gateway
#         ^--- duplicate host
#             ^--- calls Pharos::SSH::Client.new.tap(&:connect)
#                  ^--- calls Net::SSH.start
```

The extra connection does nothing, but I assume a passphrase/password for it will be prompted separately (twice?).

**Comment by kke** [comment]
Each `bastion:` also creates a new instance of `Pharos::Configuration::Bastion`, so if you have 50 hosts, each sharing the same bastion config, every one of those bastions and their `bastion.host` are separate instances, meaning there will be 100 separate ssh sessions opened to the bastion host.

```yaml
hosts:
  - address: 10.0.0.2
    bastion:
      address: 10.0.0.1  # <-- Creates a Pharos::Configuration::Bastion instance
  - address: 10.0.0.3
    bastion: 
      address: 10.0.0.1 # <-- Creates another Pharos::Configuration::Bastion instance
  - address: 10.0.0.4
    bastion: 
      address: 10.0.0.1 # <-- Creates yet another Pharos::Configuration::Bastion instance
```

This is the reason for the ~dereferencing~  of config hosts done in #1090 `config.rb` after load. There, only one connection would be made to `10.0.0..1`.
