### ISSUE TITLE
Error in step "Load cluster configuration @ <node1>

### ISSUE THREAD

**Issue by 74cmonty** [kontena/pharos-cluster#1075]
**What happened**:

Deployment on 4 nodes (KVM with Debian 9) fails in step "Load cluster configuration @ <node1>.
This is the error message displayed:
```
    got error (Excon::Error::Socket): SSL_connect returned=1 errno=0 state=SSLv3/TLS write client hello: wrong version number (OpenSSL::SSL
::SSLError)
```

The complete debug output is available [here](https://gist.github.com/74cmonty/d6193c18528d969a36ce39021f5748f3).

**What you expected to happen**:
`pharos up` should finish w/o errors.

**How to reproduce it (as minimally and precisely as possible)**:
Execute `pharos up (-d)`

**Anything else we need to know?**:

**Environment**:
- Pharos version (use `pharos --version`): pharos 2.2.1
- Cloud provider or hardware configuration: KVM with 2 Cores, 4GB RAM, 20GB disk space
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): Debian 9.7
- Others:

**cluster.yml:**

```
hosts:
  - address: "192.168.1.191"
    user: thomas
    ssh_key_path: ~/.ssh/id_rsa
    role: master
    private_interface: ens19
    environment:
      http_proxy: http://proxy:8080
      HTTP_PROXY: http://proxy:8080
      HTTPS_PROXY: http://proxy:8080
      NO_PROXY: localhost,127.0.0.1,10.97.206.0/24,192.168.1.0/24,172.31.0.0/16,172.32.0.0/16,wdf.xyz.corp
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  - address: "192.168.1.192"
    role: worker
    container_runtime: cri-o
    private_interface: ens19
    environment:
      http_proxy: http://proxy:8080
      HTTP_PROXY: http://proxy:8080
      HTTPS_PROXY: http://proxy:8080
      NO_PROXY: localhost,127.0.0.1,10.97.206.0/24,192.168.1.0/24,172.31.0.0/16,172.32.0.0/16,wdf.xyz.corp
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  - address: "192.168.1.193"
    role: worker
    private_interface: ens19
    environment:
      http_proxy: http://proxy:8080
      HTTP_PROXY: http://proxy:8080
      HTTPS_PROXY: http://proxy:8080
      NO_PROXY: localhost,127.0.0.1,10.97.206.0/24,192.168.1.0/24,172.31.0.0/16,172.32.0.0/16,wdf.xyz.corp
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  - address: "192.168.1.194"
    role: worker
    container_runtime: cri-o
    private_interface: ens19
    environment:
      http_proxy: http://proxy:8080
      HTTP_PROXY: http://proxy:8080
      HTTPS_PROXY: http://proxy:8080
      NO_PROXY: localhost,127.0.0.1,10.97.206.0/24,192.168.1.0/24,172.31.0.0/16,172.32.0.0/16,wdf.xyz.corp
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
network:
  dns_replicas: 3
  provider: weave
  service_cidr: 172.31.0.0/16
  pod_network_cidr: 172.32.0.0/16
addons:
  ingress-nginx:
     enabled: true
telemetry:
  enabled: false
audit:
  file:
    path: /var/log/kube_audit/audit.json
    max_size: 100
    max_age: 30
    max_backups: 20
```

**Comment by jnummelin** [comment]
Are all the control-plane component containers started properly on the master?

**Comment by 74cmonty** [comment]
Hm... based on the configuration in _cluster.yml_ I assume that any "control-plane component containers" are running with Docker. Therefor I can share this output of `docker ps`:
```thomas@vm191-kontena:~$ sudo docker ps
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS               NAMES
e9a3ef01e52a        177db4b8e93a                                       "kube-apiserver --au…"   About an hour ago   Up About an hour                        k8s_kube-apiserver_kube-apiserver-vm191-kontena_kube-system_36bdaab45630906eccb37c80dc2c0034_0
e5e986ab2fae        3193be46e0b3                                       "kube-scheduler --pr…"   About an hour ago   Up About an hour                        k8s_kube-scheduler_kube-scheduler-vm191-kontena_kube-system_adf0e9f9240d6befb483af27d0b14d0a_0
4abd6cb07434        b9027a78d94c                                       "kube-controller-man…"   About an hour ago   Up About an hour                        k8s_kube-controller-manager_kube-controller-manager-vm191-kontena_kube-system_b427a7d42aa99fc8c8a24cedf087b71b_0
81907f5dd1f8        registry.pharos.sh/kontenapharos/pause:3.1         "/pause"                 About an hour ago   Up About an hour                        k8s_POD_kube-apiserver-vm191-kontena_kube-system_36bdaab45630906eccb37c80dc2c0034_0
b72b70bc7f43        registry.pharos.sh/kontenapharos/pause:3.1         "/pause"                 About an hour ago   Up About an hour                        k8s_POD_kube-scheduler-vm191-kontena_kube-system_adf0e9f9240d6befb483af27d0b14d0a_0
3aba64835d4b        registry.pharos.sh/kontenapharos/pause:3.1         "/pause"                 About an hour ago   Up About an hour                        k8s_POD_kube-controller-manager-vm191-kontena_kube-system_b427a7d42aa99fc8c8a24cedf087b71b_0
0539421bc2d2        registry.pharos.sh/kontenapharos/etcd              "etcd --name=vm191-k…"   About an hour ago   Up About an hour                        k8s_etcd_etcd-vm191-kontena_kube-system_5c1f83767f610d7d0ec30aad6692634d_0
4abbd29deff5        registry.pharos.sh/kontenapharos/pause-amd64:3.1   "/pause"                 About an hour ago   Up About an hour                        k8s_POD_etcd-vm191-kontena_kube-system_5c1f83767f610d7d0ec30aad6692634d_0
```

If this information is not correct please advise.

THX

**Comment by 74cmonty** [comment]
Is the error message ```got error (Excon::Error::Socket): SSL_connect returned=1 errno=0 state=SSLv3/TLS write client hello: wrong version number (OpenSSL::SSL
::SSLError)``` misleading? Or is it pointing to the right direction?
The package version of openssl is: 1.1.0

**Comment by jnummelin** [comment]
The error indicates pharos cli cannot connect to the api server. `write client hello: wrong version number ` does sound weird though.

From the logs I see that you seem to be running the pharos cli on the master node, is that true? The downloaded access config has server set to `localhost:6443`, check what you get with `curl -k https://localhost:6443`.

**Comment by 74cmonty** [comment]
Yes, I run _pharos cli_ on the master node.
Is this not recommended?

Here's the output of curl command:
```
thomas@vm191-kontena:~$ curl -k https://localhost:6443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
```

**Comment by jakolehm** [comment]
Most likely the problem is with proxy env settings. You have set `NO_PROXY` ranges (like `192.168.1.0/24`) which are not supported by http client (excon) used by pharos cli. 

I see two options:
1. unset all proxy envs before executing pharos cli, for example `HTTP_PROXY="" http_proxy="" HTTPS_PROXY="" pharos up ..`
2. fix proxy envs

**Comment by 74cmonty** [comment]
Hi,
I'm not sure how proposal 1 should work because `pharos up` is installing required packages and I need a proxy to download these from official repo.
Can you please specify your proposal 2 as I don't understand what is wrong with my settings?
Again I need proxy settings to fetch/download data from outside of my LAN.

THX

**Comment by jnummelin** [comment]
Using option 1 would mean that the `pharos up` process would not use proxies, proxies would still be used when fetching packages etc. as they are defined in the cluster.yml for the nodes.

I think this is now kinda chicken-and-egg case regarding the proxies as you are running `pharos up ...` on the master host which will get the proxies set also by pharos.

**Comment by jakolehm** [comment]
Actually you could try "bastion" feature which forces all api communication go through given host. From the [docs](https://www.pharos.sh/docs/configuration/#hosts):
>  bastion (proxy) configuration used to connect to the host. If bastion is specified for a master host then also Kubernetes API calls are proxied through bastion ssh tunnel

Example config for the master host:
```yaml
hosts:
- address: "192.168.1.191"
    user: thomas
    ssh_key_path: ~/.ssh/id_rsa
    role: master
    bastion:
      address: "192.168.1.191"
      user: thomas
      ssh_key_path: ~/.ssh/id_rsa
    private_interface: ens19
    environment:
      http_proxy: http://proxy:8080
      HTTP_PROXY: http://proxy:8080
      HTTPS_PROXY: http://proxy:8080
      NO_PROXY: localhost,127.0.0.1,10.97.206.0/24,192.168.1.0/24,172.31.0.0/16,172.32.0.0/16,wdf.xyz.corp
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

**Comment by 74cmonty** [comment]
I started from scratch with a simplified `cluster.yml` file:
```
hosts:
  - address: "192.168.1.191"
    user: thomas
    ssh_key_path: ~/.ssh/id_rsa
    role: worker
    private_interface: ens19
  - address: "192.168.1.192"
    role: master
    private_interface: ens19
  - address: "192.168.1.193"
    role: worker
    container_runtime: cri-o
    private_interface: ens19
  - address: "192.168.1.194"
    role: worker
    container_runtime: cri-o
    private_interface: ens19
network:
  dns_replicas: 3
  provider: weave
  service_cidr: 172.31.0.0/16
  pod_network_cidr: 172.32.0.0/16
addons:
  ingress-nginx:
     enabled: true
telemetry:
  enabled: false
audit:
  file:
    path: /var/log/kube_audit/audit.json
    max_size: 100
    max_age: 30
    max_backups: 20
```
This means I dropped any environment info incl. proxy settings, ensured that path includes `/usr/local/bin:/usr/bin:/bin` and the deployed the cluster with `pharos up -c cluster.yml`.

Based on this successful deployment I will close this ticket.
