### ISSUE TITLE
ERROR: TypeError : no implicit conversion of Array into String when using full default firewalld block in cluster.yml

### ISSUE THREAD

**Issue by markkutikkanen** [kontena/pharos-cluster#1076]
**What happened**:

```
$ pharos up -d -c cluster.yml
==> KONTENA PHAROS v2.2.1+oss (Kubernetes v1.13.2)
==> Reading instructions ...
ERROR: TypeError : no implicit conversion of Array into String

```

**What you expected to happen**:

New cluster state is updated as defined in `cluster.yml`

**How to reproduce it (as minimally and precisely as possible)**:

Added default firewalld section (from Pharos docs) into cluster.yaml under network.

**Anything else we need to know?**:
- Cluster imported into Rancher 2.1.5
- If I omit open_ports and leave just 
```
  firewalld:
    enabled: true
```
it runs ok.

**Environment**:
- Pharos version (use `pharos --version`):
Above
- Cloud provider or hardware configuration:
Hetzner VMs
- OS (e.g. from /etc/os-release; both for the client and for the used nodes):
Ubuntu 18.04
- Others:

**cluster.yml:**
```
...
kube_proxy:
  mode: ipvs

network:
  provider: weave

  firewalld:
    enabled: true
    open_ports:
    - port: "22"
      protocol: tcp
      roles:
      - "*"
    - port: "80"
      protocol: tcp
      roles:
      - worker
    - port: "443"
      protocol: tcp
      roles:
      - worker
    - port: "6443"
      protocol: tcp
      roles:
      - master
    - port: "30000-32767"
      protocol: tcp
      roles:
      - "*"
    - port: "30000-32767"
      protocol: udp
      roles:
      - "*"

addons:
...
```
