### ISSUE TITLE
pharos up hangs after "Configure kubelet @ <node1> <node2> <node3> <node4>"

### ISSUE THREAD

**Issue by 74cmonty** [kontena/pharos-cluster#1084]
**What happened**:

This is a follow-up issue of #1075, means after modifying cluster.yml (by deleting any entries related to proxy) and restarting pharos up the deployment process hangs when completing phase "Configure kubelet @ <node1> <node2> <node3> <node4>".

In the debug log I can see these entries:
```
    192.168.1.192: + sleep 1
     192.168.1.194: + sleep 1
     192.168.1.192: + sleep 1
     192.168.1.194: + sleep 1
     192.168.1.192: + sleep 1
     192.168.1.194: + sleep 1
[...]
```
IP 192.168.1.192 represents <node2> and 192.168.1.194 represents <node4>.

**What you expected to happen**:
Either the deployment is finishing w/o errors or the phase is giving an error message back.

**Environment**:
- Pharos version (use `pharos --version`):  pharos 2.2.1
- Cloud provider or hardware configuration: KVM with 2 Cores, 4GB RAM, 20GB disk space
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): Debian 9.7
- Others:

**How to reproduce the issue**:
```
HTTP_PROXY="" http_proxy="" HTTPS_PROXY=""
pharos up -d -c ~/cluster.yml
```
**cluster.yml:**

```
thomas@vm191-kontena:~$ more cluster.yml
hosts:
  - address: "192.168.1.191"
    user: thomas
    ssh_key_path: ~/.ssh/id_rsa
    role: master
    private_interface: ens19
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  - address: "192.168.1.192"
    role: worker
    container_runtime: cri-o
    private_interface: ens19
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  - address: "192.168.1.193"
    role: worker
    private_interface: ens19
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  - address: "192.168.1.194"
    role: worker
    container_runtime: cri-o
    private_interface: ens19
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
network:
  dns_replicas: 3
  provider: weave
  service_cidr: 172.31.0.0/16
  pod_network_cidr: 172.32.0.0/16
addons:
  ingress-nginx:
     enabled: true
telemetry:
  enabled: false
audit:
  file:
    path: /var/log/kube_audit/audit.json
    max_size: 100
    max_age: 30
    max_backups: 20
```

The complete debug logfile is attached.
[pharos_4.log](https://github.com/kontena/pharos-cluster/files/2876729/pharos_4.log)

**Comment by 74cmonty** [comment]
I started from scratch with a simplified `cluster.yml` file:
```
hosts:
  - address: "192.168.1.191"
    user: thomas
    ssh_key_path: ~/.ssh/id_rsa
    role: worker
    private_interface: ens19
  - address: "192.168.1.192"
    role: master
    private_interface: ens19
  - address: "192.168.1.193"
    role: worker
    container_runtime: cri-o
    private_interface: ens19
  - address: "192.168.1.194"
    role: worker
    container_runtime: cri-o
    private_interface: ens19
network:
  dns_replicas: 3
  provider: weave
  service_cidr: 172.31.0.0/16
  pod_network_cidr: 172.32.0.0/16
addons:
  ingress-nginx:
     enabled: true
telemetry:
  enabled: false
audit:
  file:
    path: /var/log/kube_audit/audit.json
    max_size: 100
    max_age: 30
    max_backups: 20
```
This means I dropped any environment info incl. proxy settings, ensured that path includes `/usr/local/bin:/usr/bin:/bin` and the deployed the cluster with `pharos up -c cluster.yml`.

Based on this successfull deployment I will close this ticket.
