### ISSUE TITLE
Option to configure custom DEB/RPM repository

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#1251]
**What would you like to be added**:

An option to configure custom DEB/RPM repository for Pharos packages.

**Why is this needed**:

Would make airgapped setups even more easier.

**Example cluster.yml**:

```yaml
hosts:
- address: 1.1.1.1
  role: master
  package_repositories:
  - name: pharos.repo
    contents: |
      [kontena-pharos]
      name=kontena-pharos
      baseurl=http://my.local.mirror/pharos-rpm
      gpgcheck=0
      repo_gpgcheck=1
      enabled=1
      gpgkey=https://bintray-pk.pharos.sh?username=bintray
- address: 2.2.2.2
  role: worker
  package_repositories:
  - name: pharos.list
    contents: |
      deb http://my.local.mirror/pharos-debian stretch main
```
