### ISSUE TITLE
On prem cluster behind proxy , networking is broken regardless of network plugin used

### ISSUE THREAD

**Issue by iahmad-khan** [kontena/pharos-cluster#1258]
The NO_PROXY settings in cluster.yml doesn't work , because it has to be in lower case no_proxy in kubelet service file.

Even if one put no_proxy in cluster.yml , pharos will convert it to upper case on the cluster.

It took me many hours to try different configurations , mtu values , network plugins etc.

Finally , I just inserted  the ip address manually , in no_proxy env section of kube-api service systemd service file, /etc/kubernetes/manifests/kube-apiserver.yaml

**Comment by kke** [comment]
Did you have 

```
control_plane:
  use_proxy: true
```

in cluster.yml?

There shouldn't be anything that changes `no_proxy` to `NO_PROXY`, which file did you see it end up in as `NO_PROXY`?

**Comment by iahmad-khan** [comment]
So I tried both no_proxy and NO_PROXY in cluster.yml , but the result change is NO_PROXY in this file:
/etc/kubernetes/manifests/kube-apiserver.yaml

**Comment by iahmad-khan** [comment]
Can you just paste the correct no proxy seetings for some network , lets say: 172.32.0.0/24

**Comment by iahmad-khan** [comment]
This setting is not working:

```
hosts:
  - address: 10.3.11.69
    user: root
    role: master
    ssh_key_path: ~/.ssh/id_rsa
    environment:
      http_proxy: http://example.com:3128                 
      HTTP_PROXY: http://example.com:3128                 
      no_proxy: localhost,127.0.0.1,.example.com,172.31.0.0/24,172.32.0.0/24
```

**Comment by iahmad-khan** [comment]
How I can exclude a whole subnet , or whole pod network from proxy?

**Comment by jnummelin** [comment]
hmm, I just tried with:
```
hosts:
- address: <public IP of master>
  private_address: 10.133.78.32
  private_interface:
  role: master
  user: root
  container_runtime: docker
  environment:
    HTTPS_PROXY: http://<proxy IP>:8888
    HTTP_PROXY: http://<proxy IP>:8888
    NO_PROXY: localhost,0,1,2,3,4,5,6,7,8,9,.cluster.local
    http_proxy: http://<proxy IP>:8888
    https_proxy: http://<proxy IP>:8888
    no_proxy: localhost,0,1,2,3,4,5,6,7,8,9,.cluster.local
- address: <public IP of worker>
  private_address: 10.133.78.171
  private_interface:
  role: worker
  user: root
  container_runtime: docker
  environment:
    HTTPS_PROXY: http://<proxy IP>:8888
    HTTP_PROXY: http://<proxy IP>:8888
    NO_PROXY: localhost,0,1,2,3,4,5,6,7,8,9,.cluster.local
    http_proxy: http://<proxy IP>:8888
    https_proxy: http://<proxy IP>:8888
    no_proxy: localhost,0,1,2,3,4,5,6,7,8,9,.cluster.local
network:
  provider: weave
  service_cidr: 10.96.0.0/12
  pod_network_cidr: 10.32.0.0/12
```

Everything works as expected.

I do not see any proxy settings on `/etc/kubernetes/manifests/kube-apiserver.yaml` as I shouldn't either since I didn't specify `use_proxy: true` for control plane.
```
root@pharos-master-0:~# grep -i proxy /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
```

Would you mind testing this with 2.3.3 which we released today, that contains some fixes for the proxy settings. https://github.com/kontena/pharos-cluster/releases/tag/v2.3.3
