### ISSUE TITLE
Kontena Storage: does not discover tainted nodes

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#1384]
**What happened**:

Cluster has storage nodes tainted and kontena-storage is configured to use these tainted nodes. This does not work because rook does not do discovery on any tainted nodes.

**cluster.yml:**

```yaml
  kontena-storage:
    enabled: true
    data_dir: /var/lib/kontena-storage
    storage:
      use_all_nodes: true
      device_filter: ^sd[c-d]
    placement:
      all:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/storage
                operator: In
                values:
                - ceph
        tolerations:
          - key: kontena.io/storage
            effect: NoSchedule
```
