### ISSUE TITLE
Annotations for Kontena Lens addon

### ISSUE THREAD

**Issue by HristoA** [kontena/pharos-cluster#1438]
**What would you like to be added**:
Option to add `annotations` like `nginx.ingress.kubernetes.io/whitelist-source-range: "XXX"` to Kontena Lens addon
**Why is this needed**:
Security protection of control unit

**Example cluster.yml**:
 

```
kontena-lens:
    enabled: true
    name: xxxx
      ingress:
        host: xxxxx
        tls:
          enabled: true
          email: xxxx@xxxx.xx
      annotations:
         nginx.ingress.kubernetes.io/whitelist-source-range: "XXX.XXX.XXX.XXX"
```
