### ISSUE TITLE
Pharos network default and docker improvment

### ISSUE THREAD

**Issue by ssimk0** [kontena/pharos-cluster#1490]
**What happened**:
Hi,
I found two problems in newest pharos cli when I start cluster with `pharos up` without network.provider, and after that I want reset cluster `pharos reset` I get error:

```
==> Invalid configuration:
network.provider: can't change network.provider from  to custom

```
I need add  manualy network.provider to pharos-config in kube-system also after that I have docker service stop and when I run again `pharos up` with docker service stopped command hangs on:

```
   [node2] Waiting for etcd to respond ...
   [node1] Waiting for etcd to respond ...
   [node3] Waiting for etcd to respond ...
```

**What you expected to happen**:
I want have network.provider setted in pharos-config when I don't specify it or fix pharos reset to don't require it. Also it will be nice when pharos up be able check docker service status and start it if is down or let you know and don't hang up on etcd respond

**How to reproduce it (as minimally and precisely as possible)**:
use config only with host setup without network run pharos up -> pharos reset -> pharos up

**Anything else we need to know?**:

**Environment**:
- Pharos version (use `pharos --version`): 2.4.7
- Cloud provider or hardware configuration: 3x HP proliant DL360 
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): ubuntu 18.04
- Others:

**cluster.yml:**

```
hosts:
  - address: xx.xx.xx.xx
    role: master
    taints: []
  - address:  xx.xx.xx.xx
    role: master
    taints: []
  - address: xx.xx.xx.xx
    role: master
    taints: []


```
