### ISSUE TITLE
PVC with type RWM write error: Filename too long

### ISSUE THREAD

**Issue by HristoA** [kontena/pharos-cluster#1494]
**What happened**:
On pod shell with mounted RWM PVC i execute:
```bash
bash-4.4# echo "test" > text.txt
bash: echo: write error: Filename too long
bash-4.4# ls -la
total 4
drwxr-xr-x    1 root     root             1 Oct 10 08:52 .
drwxr-xr-x    1 root     root          4096 Oct 10 08:16 ..
-rw-r--r--    1 root     root             0 Oct 10 08:52 text.txt
```
File is created but empty. File is replicated to all pods that use it.

    Pod use node:10.16.3-alpine image.
    Host nodes are with type ext4

I think that is related in some way to CephFS but for now not found the reason for this error.
Thanks

**What you expected to happen**:
To not have limits on files and all to work correctly 
**How to reproduce it (as minimally and precisely as possible)**:
Add PVC with type RWM to some deployment and enter to pod shell.

**Anything else we need to know?**:

**Environment**:
- Pharos version (use `pharos --version`): 2.4.8
- Cloud provider or hardware configuration: Cloud VPS provider, 3 master/ 3 worker nodes, 40GB SSD each node
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**cluster.yml:**

```yml
kontena-storage:
    enabled: true
    data_dir: /home/kontena-storage
    storage:
      use_all_nodes: true
      # It's highly recommended to set directories and/or device_filter,
      # otherwise expanding storage does not work properly (see https://github.com/rook/rook/issues/1957)
      directories:
      - path: /home/ceph
    pool:
      replicated:
        size: 3
    dashboard:
      enabled: true
    filesystem:  # Shared filesystem - ReadWriteMany persistent volumes
      enabled: true
      pool:
        replicated:
          size: 3
```
