### ISSUE TITLE
Netpols broken again

### ISSUE THREAD

**Issue by tipruzs** [kontena/pharos-cluster#1504]
**What happened**:

Traffic from ingress-nginx gets dropped, when network policies are in place and ingress-nginx and the target pod are not on the same host.

weave-npc logs show dropped request.

**What you expected to happen**:

Traffic should pass if networkpolicy matches

**How to reproduce it (as minimally and precisely as possible)**:

Minimal Cluster (1 master, 2 worker) with default weave and ingress-nginx enabled. Deploy a sample http demo and enable networkpolicies. traffic should pass from both worker nodes, but only when node matches nginx and http demo, the request is successful.

**Anything else we need to know?**:

Did work as of Version 2.4.5 and got broken with 2.4.6

Similar behavior was seen here #1302 

**Environment**:
- pharos 2.4.9+oss
- Hetzner Cloud (Terraform)
- Ubuntu 18.04

**cluster.yml:**

```
name: pharos-lab
cloud:
  provider: pharos
network:
  provider: weave
  node_local_dns_cache: true
  service_cidr: 10.96.0.0/12
  pod_network_cidr: 10.32.0.0/12
  weave:
    no_masq_local: true
  firewalld:
    enabled: true
telemetry:
  enabled: false
addons:
  ingress-nginx:
    enabled: true
```
