### ISSUE TITLE
Caligo egress fail

### ISSUE THREAD

**Issue by HristoA** [kontena/pharos-cluster#1511]
**What happened**:
Trying https://docs.projectcalico.org/v3.1/getting-started/kubernetes/tutorials/advanced-policy tutorial stuck on Step5

**What you expected to happen**:
Tutorial to be successfully finish and Egress rule to work correct 

**How to reproduce it (as minimally and precisely as possible)**:
Follow tutorial
**Anything else we need to know?**:
Simialr case with minicube: https://github.com/projectcalico/calico/issues/2016
**Environment**:
- Pharos version (use `pharos --version`): 2.4.8
- Cloud provider or hardware configuration: VPS`s from Hetzner 
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): Ubuntu 18.0.4
- Others:

Verification of Step 5 return:
```bash
/ # nslookup nginx
;; connection timed out; no servers could be reached

/ # nslookup google.com
;; connection timed out; no servers could be reached
```

**cluster.yml:**
```tml
network:
  provider: calico
  dns_replicas: 3
  node_local_dns_cache: true
  service_cidr: 10.96.0.0/12
  pod_network_cidr: 10.32.0.0/12
  firewalld:
    enabled: true
```

**Comment by HristoA** [comment]
We figure out what is happening thanks to @jnummelin 
My configuration has `node_local_dns_cache: true` and this is the case why **egress** '_not_' work correctly. 

Right ways is to add static IP of local DNS that is : `169.254.20.10` to egress rules.
Working **Network Police** for Step 5, from tutorial is:
```yml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: advanced-policy-demo
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - ipBlock:
         cidr: 169.254.20.10/32
    ports:
    - protocol: UDP
      port: 53
```
