### ISSUE TITLE
Lens Invalid SSL

### ISSUE THREAD

**Issue by scottrobertson** [kontena/pharos-cluster#1521]
Hey

Using lens via the following config:

```
addons:
  kontena-lens:
    enabled: true
    ingress:
      host: 'lens.example.com'
      tls:
        enabled: true
        email: 'scott@example.com'
```

It's been working perfectly, but i just dropped the cluster and created again, and now i am getting `NET::ERR_CERT_INVALID` when visiting `lens.example.com`. Is there a way to reissue the cert?

pharos version 2.4.10
