### ISSUE TITLE
Removing host labels does not remove labels from the kube node

### ISSUE THREAD

**Issue by SpComb** [kontena/pharos-cluster#268]
Re-running `pharos-cluster up` with modified `hosts[*].labels` works for adding or changing labels, but removing a label from the config does not remove the label from the node.

Similarly, removing the entire `hosts[*].labels` hash does not remove any labels from the node either ("No labels set ...").

### Starting point

```yaml
hosts:
  - address: 167.99.36.158
    user: root
    role: master
```

```
root@terom-kupo-master:~# kubectl get nodes --show-labels
NAME                STATUS    ROLES     AGE       VERSION   LABELS
terom-kupo-node1    Ready     master    18h       v1.9.6    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=terom-kupo-node1,node-role.kubernetes.io/master=
```

### Add one label
```yaml
hosts:
  - address: 167.99.36.158
    user: root
    role: master
    labels:
      test: "true"
```

```
root@terom-kupo-master:~# kubectl get nodes --show-labels
NAME                STATUS    ROLES     AGE       VERSION   LABELS
terom-kupo-node1    Ready     master    18h       v1.9.6    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=terom-kupo-node1,node-role.kubernetes.io/master=,test=true
```

### Add second label
```yaml
hosts:
  - address: 167.99.36.158
    user: root
    role: master
    labels:
      test: "true"
      test2: "false"
```

```
root@terom-kupo-master:~# kubectl get nodes --show-labels
NAME                STATUS    ROLES     AGE       VERSION   LABELS
terom-kupo-node1    Ready     master    18h       v1.9.6    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=terom-kupo-node1,node-role.kubernetes.io/master=,test2=false,test=true
```

### Remove second label

```yaml
hosts:
  - address: 167.99.36.158
    user: root
    role: master
    labels:
      test: "true"
```

```
root@terom-kupo-master:~# kubectl get nodes --show-labels
NAME                STATUS    ROLES     AGE       VERSION   LABELS
terom-kupo-node1    Ready     master    18h       v1.9.6    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=terom-kupo-node1,node-role.kubernetes.io/master=,test2=false,test=true
```

The second label is still there.
