### ISSUE TITLE
Attempting to create cluster yields NoMethodError : undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by mthird** [kontena/pharos-cluster#281]
I'm attempting to stand up a multi-master cluster on DO but receiving the following error:

```
==> Reading instructions ...
==> Sharpening tools ...
NoMethodError : undefined method 'each' for nil:NilClass
```

I've simplified the setup down to a single master but still receive the same error:

```
hosts:
  - address: "165.227.xxx.xxx"
    private_address: "10.132.xxx.xxx"
    role: master
    user: root
    ssh_key_path: ~/.ssh/id_rsa
  - address: "165.227.xxx.xxx"
    private_address: "10.132.xxx.xxx"
    role: worker
    user: root
  - address: "165.227.xxx.xxx"
    private_address: "10.132.xxx.xxx"
    role: worker
    user: root
network:
  trusted_subnets:
    - "10.132.0.0/16"
```

This is running on WSL on Windows 10 Spring Creators Update.
