### ISSUE TITLE
Add option to set Let's Encrypt issuer (cert-manager)

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#3]
Resource file example:

```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: <%= server %>
    # Email address used for ACME registration
    email: <%= email %>
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    http01: {}
```
