### ISSUE TITLE
cert-manager: create ca-issuer automatically

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#406]
With option to turn it off.

**Comment by jnummelin** [comment]
I guess this should take the CA key and cert as options. The config for that could be something like:
```
ca_issuer:
  key: /path/to/key # required
  cert: /path/to/ca_cert # required
  name: some_name # optional, can be defaulted to e.g. ca-issuer
  secret_name: name_of_the_ca_secret # optional, can be defaulted to e.g. ca-issuer-secret
```
