### ISSUE TITLE
Add prometheus scraping to CoreDNS

### ISSUE THREAD

**Issue by swade1987** [kontena/pharos-cluster#613]
Having the ability to scrape metrics from CoreDNS (a core component of the cluster) by default is really a must have set up in my opinion.

You'd need to add the following to the YAML file deployed to make this possible:

```
metadata:
      annotations:
        prometheus.io/port: "9153"
        prometheus.io/scrape: "true"
```

Also, you may want to add preferred pod anti-affinity (see below)

```
affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - coredns
              topologyKey: kubernetes.io/hostname
```
