### ISSUE TITLE
Add configurability for admission controllers

### ISSUE THREAD

**Issue by jnummelin** [kontena/pharos-cluster#644]
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers

Would be nice to have the possibility to define in cluster.yml which admission controllers are enabled. The enabled-by-default list is (as of 1.11):
```
NamespaceLifecycle
LimitRanger
ServiceAccount
PersistentVolumeLabel
DefaultStorageClass
DefaultTolerationSeconds
MutatingAdmissionWebhook
ValidatingAdmissionWebhook
ResourceQuota
Priority
```

I guess the biggest "problem" is how to handle the configuration of the admission controller as some of them require extra config files etc. in place.

All the ac's should be configurable via single file, which in turn point to other files:
```
kind: AdmissionConfiguration
apiVersion: apiserver.k8s.io/v1alpha1
plugins:
- name: EventRateLimit
  path: eventconfig.yaml
...
```

So it might make sense to have something like this in the cluster.yml:
```
admission_controllers:
  - name: EventRateLimit
    config: path/to/config
  - name: PodSecurityPolicy
  - name: SomeOther
```
So the config file path would be optional as not all ac's need those at all.
