### ISSUE TITLE
Flaky spec Pharos::Host::Configurer#register_config

### ISSUE THREAD

**Issue by kke** [kontena/pharos-cluster#863]
Depends on execution order

Fixed in #799

```
Failures:

  1) Pharos::Host::Configurer#register_config registers multiple versions to configs
     Failure/Error:
       expect(
         described_class.config_for_os_release(
           Pharos::Configuration::OsRelease.new(id: 'test', version: '1.0.0')
         )
       ).not_to be_nil

       expected: not nil
            got: nil
     # ./bundler/ruby/2.5.0/gems/rspec-support-3.8.0/lib/rspec/support.rb:97:in `block in <module:Support>'
     # ./bundler/ruby/2.5.0/gems/rspec-support-3.8.0/lib/rspec/support.rb:106:in `notify_failure'
     # ./bundler/ruby/2.5.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # ./bundler/ruby/2.5.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # ./bundler/ruby/2.5.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/handler.rb:72:in `block in handle_matcher'
     # ./bundler/ruby/2.5.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./bundler/ruby/2.5.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/handler.rb:70:in `handle_matcher'
     # ./bundler/ruby/2.5.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/expectation_target.rb:78:in `not_to'
     # ./spec/pharos/host/configurer_spec.rb:22:in `block (3 levels) in <top (required)>'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `instance_exec'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # ./spec/spec_helper.rb:122:in `block (2 levels) in <top (required)>'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:373:in `execute_with'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # ./spec/spec_helper.rb:112:in `block (2 levels) in <top (required)>'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:373:in `execute_with'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:607:in `run_around_example_hooks_for'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `map'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `block in run'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `map'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `run'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `map'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
     # ./bundler/ruby/2.5.0/gems/rspec-core-3.8.0/exe/rspec:4:in `<top (required)>'
     # ./bundler/ruby/2.5.0/bin/rspec:23:in `load'
     # ./bundler/ruby/2.5.0/bin/rspec:23:in `<top (required)>'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
     # /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
     # /usr/local/bundle/bin/bundle:23:in `load'
     # /usr/local/bundle/bin/bundle:23:in `<main>'
```
