### ISSUE TITLE
Pharos-Cluster force unencrypt all ssh keys

### ISSUE THREAD

**Issue by denji** [kontena/pharos-cluster#875]
pharos-cluster forces unencrypt all keys that are in the ~/.ssh/config (`Host *`, `Host ...`) when run `./pharos-cluster-linux-amd64-2.0.4 [build/up]`  

* `cluster.yml` was set the path `ssh_key_path`.

```yml
hosts:
  - address: "10.0.0.40"
    user: root
    role: master
    ssh_key_path: ~/.ssh/k8s_ed25519
  - address: "10.0.3.5"
    user: root
    role: worker
    ssh_key_path: ~/.ssh/k8s_ed25519
  - address: "10.0.3.6"
    user: root
    role: worker
    ssh_key_path: ~/.ssh/k8s_ed25519
  - address: "10.0.3.7"
    user: root
    role: worker
    ssh_key_path: ~/.ssh/k8s_ed25519
addons:
  ingress-nginx:
    enabled: true
```
