### ISSUE TITLE
Support multiple master nodes in different regions

### ISSUE THREAD

**Issue by ImmaBird** [kontena/pharos-cluster#890]
**What would you like to be added**:
I would like to be able to put the masters for my cluster in different regions.

**Why is this needed**:
This is needed for high availability, for example if there is a geographical outage and one region went down you could have masters in entirely different regions that would not be affected by the outage and therefore your cluster would remain up.

**Example cluster.yml**:
```
hosts:
  - address: "Public IP address"
    private_interface: ens5
    user: ubuntu
    role: master
    labels:
      failure-domain.beta.kubernetes.io/region: regionA
  - address: "Public IP address"
    private_interface: ens5
    user: ubuntu
    role: master
    labels:
      failure-domain.beta.kubernetes.io/region: regionB
  - address: "Public IP address"
    private_interface: ens5
    user: ubuntu
    role: master
    labels:
      failure-domain.beta.kubernetes.io/region: regionC
  - address: "Public IP address"
    private_interface: ens5
    user: ubuntu
    role: worker
    labels:
      failure-domain.beta.kubernetes.io/region: regionA
  - address: "Public IP address"
    private_interface: ens5
    user: ubuntu
    role: worker
    labels:
      failure-domain.beta.kubernetes.io/region: regionB
network:
  provider: weave
```

The masters `failure-domain.beta.kubernetes.io/region` label are different.
```
hosts:
  - address: "Public IP address"
    role: master
    labels:
      failure-domain.beta.kubernetes.io/region: regionA
  - address: "Public IP address"
    role: master
    labels:
      failure-domain.beta.kubernetes.io/region: regionB
```
