### ISSUE TITLE
Add annotations to Lens Ingress

### ISSUE THREAD

**Issue by Timer** [kontena/pharos-cluster#897]
**What would you like to be added**:
The ability to add annotations to the Ingress object for Lens.

**Why is this needed**:
When using a different ingress controller (or multiple) it's necessary to specify `kubernetes.io/ingress.class`.

https://github.com/kontena/pharos-cluster/blob/master/non-oss/pharos_pro/addons/kontena-lens/resources/12-ingress.yml.erb

i.e.
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: 'traefik-dmz'
```
