### ISSUE TITLE
Error: SSH exec failed with code 100: configure-cri-o.sh

### ISSUE THREAD

**Issue by 74cmonty** [kontena/pharos-cluster#904]
**What happened**:
Running cluster deployment in multi-node setup.
The 4 nodes are running with Debian 9.

This fails with an error:
`SSH exec failed with code 100: configure-cri-o.sh`

**What you expected to happen**:
Completing cluster deployment w/o errors.

**How to reproduce it (as minimally and precisely as possible)**:

1. chpharos use 2.0.4
2. pharos up -c cluster.yml

**Environment**:
- Pharos version (use `pharos --version`): 2.0.4
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): Debian 9.6

**Additional information:**
I have defined a simple apt-hook to run `update-grub` after every `apt install` execution.
```
thomas@vm191-kontena:~$ more /etc/apt/apt.conf.d/81updategrubhook
DPkg::Post-Invoke {"/usr/sbin/update-grub";};
```
There's no issue with this hook when calling `apt install` in console.

Complete output of `pharos up ...` in console here: [pharos_up_output-txt](https://gist.github.com/74cmonty/ff868c44341fff9f34ff7d792b4a5629#file-pharos_up_output-txt)

**cluster.yml:**
```
hosts:
  - address: "10.97.206.191"
    user: thomas
    ssh_key_path: /home/thomas/.ssh/id_rsa.pub
    role: master
    environment:
      http_proxy: http://proxy:8080
      HTTP_proxy: http://proxy:8080
      HTTPS_PROXY: http://proxy:8080
      NO_PROXY: localhost,127.0.0.1,10.97.206.0/24,192.168.1.0/24,wdf.xyz.corp
    container_runtime: cri-o
  - address: "10.97.206.192"
    role: worker
    container_runtime: cri-o
  - address: "10.97.206.193"
    role: worker
    container_runtime: cri-o
  - address: "10.97.206.194"
    role: worker
    container_runtime: cri-o
network:
  dns_replicas: 2
  service_cidr: 10.10.0.0/12
  provider: weave
audit:
  file:
    path: /var/log/kube_audit/audit.json
    max_size: 100
    max_age: 30
    max_backups: 20
admission_plugins:
  - name: AlwaysPullImages
    enabled: true
  - name: LimitRanger
    enabled: false
addons:
  ingress-nginx:
    enabled: true
    node_selector:
      # only provision to nodes having the label "zone: dmz"
      zone: dmz
    configmap:
      # see all supported options: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/configmap.md
      load-balance: least_conn
host-upgrades:
    enabled: true
    interval: 7d
```

**Execution of _pharos up -d -c cluster.yml_:**
```
[...]
    [vm193-kontena] got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 100: configure-cri-o.sh
+ set -e
+ . /usr/local/share/pharos/util.sh
++ mktemp /tmp/crio-service.XXXXXX
+ tmpfile=/tmp/crio-service.aTefMs
+ cat
+ diff /tmp/crio-service.aTefMs /etc/systemd/system/crio.service
+ rm /tmp/crio-service.aTefMs
+ mkdir -p /etc/systemd/system/crio.service.d
+ '[' -n '' ']'
+ '[' -f /etc/systemd/system/crio.service.d/http-proxy.conf ']'
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ apt-mark unhold cri-o
cri-o was already not hold.
+ apt-get install -y cri-o=1.11.9
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  conntrack libgpgme11
The following NEW packages will be installed:
  conntrack cri-o libgpgme11
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/16.8 MB of archives.
After this operation, 54.3 MB of additional disk space will be used.
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
Config is in use.
/usr/sbin/update-grub: 3: exec: grub-mkconfig: not found
E: Sub-process /usr/bin/dpkg returned an error code (2)
E: Problem executing scripts DPkg::Post-Invoke '/usr/sbin/update-grub'
E: Sub-process returned an error code
    /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.4/lib/pharos/ssh/remote_command.rb:66:in `run!'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.4/lib/pharos/ssh/client.rb:86:in `exec!'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.4/lib/pharos/ssh/client.rb:100:in `exec_script!'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.4/lib/pharos/host/configurer.rb:83:in `exec_script'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.4/lib/pharos/host/debian/debian_stretch.rb:47:in `configure_container_runtime'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.4/non-oss/pharos_pro/phases/configure_host.rb:11:in `configure_container_runtime'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.4/lib/pharos/phases/configure_host.rb:26:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.4/lib/pharos/phase_manager.rb:92:in `block in apply'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.4/lib/pharos/phase_manager.rb:53:in `yield_phase_with_retry'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.4/lib/pharos/phase_manager.rb:34:in `block (2 levels) in run_parallel'
    [vm193-kontena] retrying after 1 seconds ...
    0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
    Need to get 0 B/16.8 MB of archives.
    After this operation, 54.3 MB of additional disk space will be used.
    dpkg: warning: 'ldconfig' not found in PATH or not executable
    dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
    dpkg: error: 2 expected programs not found in PATH or not executable
    Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
    Config is in use.
    /usr/sbin/update-grub: 3: exec: grub-mkconfig: not found
    E: Sub-process /usr/bin/dpkg returned an error code (2)
    E: Problem executing scripts DPkg::Post-Invoke '/usr/sbin/update-grub'
    E: Sub-process returned an error code
    ! 100
[...]
```

**Comment by 74cmonty** [comment]
**Workaround:**
Include `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin` in `/etc/environment` on any cluster node.

**Comment by kke** [comment]
You can do:
```
hosts:
   - address: 1.2.3.4
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

It should usually come from `/etc/login.defs `ENV_SUPATH` correctly, but if you have a  different kind of `PATH` set up in `/etc/envinroment` without the `sbin`s, I think it will overwrite the default from `ENV_SUPATH`.
