### ISSUE TITLE
Error in step "Configure kube client @ <master>: SSL_connect returned=1 errno=0 state=SSLv3/TLS write client hello: wrong version number (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by 74cmonty** [kontena/pharos-cluster#908]
**What happened**:
The deployment stops in step "Configure kube client @ vm191-kontena (=master).
The predecessor step "Configure master @ vm191-kontena" finished w/o errors.
The following services are running on master:
```
thomas@vm191-kontena:~$ sudo netstat -tulpen
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       Benutzer   Inode      PID/Program name
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      0          824257     30326/kube-schedule
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      0          818111     28430/etcd
tcp        0      0 10.97.206.191:2379      0.0.0.0:*               LISTEN      0          818103     28430/etcd
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      0          823207     30173/kube-controll
tcp        0      0 10.97.206.191:2380      0.0.0.0:*               LISTEN      0          818102     28430/etcd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          11934      502/sshd
tcp        0      0 127.0.0.1:10010         0.0.0.0:*               LISTEN      0          813560     27301/crio
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      1000       608832     3223/sshd: thomas@p
tcp        0      0 127.0.0.1:6011          0.0.0.0:*               LISTEN      1000       807500     25298/sshd: thomas@
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      0          820338     28920/kubelet
tcp6       0      0 :::10250                :::*                    LISTEN      0          820345     28920/kubelet
tcp6       0      0 :::6443                 :::*                    LISTEN      0          823747     30189/kube-apiserve
tcp6       0      0 :::10257                :::*                    LISTEN      0          823211     30173/kube-controll
tcp6       0      0 :::22                   :::*                    LISTEN      0          11945      502/sshd
tcp6       0      0 ::1:6010                :::*                    LISTEN      1000       608831     3223/sshd: thomas@p
tcp6       0      0 ::1:6011                :::*                    LISTEN      1000       807499     25298/sshd: thomas@
```

This is the error message in console:
```
    [vm191-kontena] got error (Excon::Error::Socket): SSL_connect returned=1 errno=0 state=SSLv3/TLS write client hello: wrong version number (OpenSSL::SSL::SSLError)
    /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/ssl_socket.rb:118:in `connect_nonblock'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/ssl_socket.rb:118:in `initialize'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:429:in `new'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:429:in `socket'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:111:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/mock.rb:48:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:260:in `request'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.6.3/lib/k8s/transport.rb:223:in `request'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.6.3/lib/k8s/transport.rb:288:in `get'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.6.3/lib/k8s/client.rb:80:in `api_groups!'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.6.3/lib/k8s/client.rb:89:in `api_groups'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.6.3/lib/k8s/client.rb:97:in `apis'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/phases/configure_client.rb:47:in `client_prefetch'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/phases/configure_client.rb:23:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/phase_manager.rb:88:in `block in apply'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/phase_manager.rb:52:in `yield_phase_with_retry'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/phase_manager.rb:43:in `block in run_serial'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/phase_manager.rb:42:in `map'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/phase_manager.rb:42:in `run_serial'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/phase_manager.rb:72:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/phase_manager.rb:85:in `apply'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/cluster_manager.rb:148:in `apply_phase'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/cluster_manager.rb:94:in `apply_phases'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/up_command.rb:41:in `configure'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/up_command.rb:20:in `block in execute'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/up_command.rb:19:in `chdir'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/up_command.rb:19:in `execute'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/command.rb:16:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/lib/pharos/command.rb:16:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.0.rc.2/bin/pharos-cluster:12:in `<top (required)>'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/bin/pharos-cluster:23:in `load'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/bin/pharos-cluster:23:in `<main>'
    [vm191-kontena] retrying after 16 seconds ...
```

You can check the debug trace for this step [here](https://gist.github.com/74cmonty/364b4a68838a988eeb4f0cf6f76b38cd).

**What you expected to happen**:
Deployment process to finish w/o errors.

**How to reproduce it (as minimally and precisely as possible)**:

1. chpharos use 2.1.0-rc.2
2. pharos up -c cluster.yml

**Anything else we need to know?**:
I can ssh to any other node w/o entering password as user thomas.
I can sudo on any other node w/o entering password as user thomas.

**Environment**:
- Pharos version (use `pharos --version`): pharos-cluster 2.1.0-rc.2
- Cloud provider or hardware configuration: 4x virtual machine (KVM)
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): Debian 9.6
- Others:

**cluster.yml:**

```
hosts:
  - address: "10.97.206.191"
    user: thomas
    ssh_key_path: /home/thomas/.ssh/id_rsa.pub
    role: master
    environment:
      http_proxy: http://proxy:8080
      HTTP_proxy: http://proxy:8080
      HTTPS_PROXY: http://proxy:8080
      NO_PROXY: localhost,127.0.0.1,10.97.206.0/24,192.168.1.0/24,wdf.xyz.corp
    container_runtime: cri-o
  - address: "10.97.206.192"
    role: worker
    container_runtime: cri-o
  - address: "10.97.206.193"
    role: worker
    container_runtime: cri-o
  - address: "10.97.206.194"
    role: worker
    container_runtime: cri-o
network:
  dns_replicas: 2
  service_cidr: 10.10.0.0/12
  provider: weave
audit:
  file:
    path: /var/log/kube_audit/audit.json
    max_size: 100
    max_age: 30
    max_backups: 20
admission_plugins:
  - name: AlwaysPullImages
    enabled: true
  - name: LimitRanger
    enabled: false
addons:
  ingress-nginx:
    enabled: true
    node_selector:
      # only provision to nodes having the label "zone: dmz"
      zone: dmz
    configmap:
      # see all supported options: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/configmap.md
      load-balance: least_conn
host-upgrades:
    enabled: true
    interval: 7d
```
