### ISSUE TITLE
Error in deployment step: Join nodes @ <node02> <node03> <node04> - Failed to connect to API Server "localhost:6443": token id "e19fc7" is invalid for this cluster or it has expired.

### ISSUE THREAD

**Issue by 74cmonty** [kontena/pharos-cluster#912]
**What happened**:
I start cluster deployment with command `NO_PROXY=localhost,127.0.0.1,10.97.206.191 pharos up -d -c cluster.yml`.

In step "Join nodes @ <node02> <node03> <node04>" I get this error:
```
    [discovery] Trying to connect to API Server "localhost:6443"
    [discovery] Created cluster-info discovery client, requesting info from "https://localhost:6443"
    [discovery] Failed to connect to API Server "localhost:6443": token id "e19fc7" is invalid for this cluster or it has expired. Use "kubeadm token create" on the mas
    [discovery] Trying to connect to API Server "localhost:6443"
    [discovery] Created cluster-info discovery client, requesting info from "https://localhost:6443"
    [discovery] Failed to connect to API Server "localhost:6443": token id "e19fc7" is invalid for this cluster or it has expired. Use "kubeadm token create" on the master node to creating a new valid token
```
I must disrupt the console (Ctrl+C) in order to get back control of console.

You can check the debug trace for the relevant step [here](https://gist.github.com/74cmonty/f12cf772189e86189435e65dacd3dc37#file-pharos_debug_trace_kubectl-txt).

**How to reproduce it (as minimally and precisely as possible)**:
1. chpharos use 2.1.0-rc.2
2. NO_PROXY=localhost,127.0.0.1,10.97.206.191 pharos up -d -c cluster.yml

**Anything else we need to know?**:
I created another token with this command, but the deployment still reports this error.
```
thomas@vm191-kontena:~$ kubeadm token create
I1210 16:17:59.424363    8270 version.go:236] remote version is much newer: v1.13.0; falling back to: stable-1.12
vhgprc.aqz1qitnchd0mnij
```
**Environment**:
- Pharos version (use `pharos --version`): pharos v2.1.0-rc.2
- Cloud provider or hardware configuration: 4x virtual machine (KVM)
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): Debian 9.6
- Others:

**cluster.yml:**
```
hosts:
  - address: "10.97.206.191"
    user: thomas
    ssh_key_path: /home/thomas/.ssh/id_rsa.pub
    role: master
    environment:
      http_proxy: http://proxy:8080
      HTTP_proxy: http://proxy:8080
      HTTPS_PROXY: http://proxy:8080
      NO_PROXY: localhost,127.0.0.1,10.97.206.0/24,192.168.1.0/24,wdf.xyz.corp
    container_runtime: cri-o
  - address: "10.97.206.192"
    role: worker
    container_runtime: cri-o
  - address: "10.97.206.193"
    role: worker
    container_runtime: cri-o
  - address: "10.97.206.194"
    role: worker
    container_runtime: cri-o
network:
  dns_replicas: 2
  service_cidr: 10.10.0.0/12
  provider: weave
audit:
  file:
    path: /var/log/kube_audit/audit.json
    max_size: 100
    max_age: 30
    max_backups: 20
admission_plugins:
  - name: AlwaysPullImages
    enabled: true
  - name: LimitRanger
    enabled: false
addons:
  ingress-nginx:
    enabled: true
    node_selector:
      # only provision to nodes having the label "zone: dmz"
      zone: dmz
    configmap:
      # see all supported options: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/configmap.md
      load-balance: least_conn
host-upgrades:
    enabled: true
    interval: 7d
```
