### ISSUE TITLE
Allow to use custom network provider

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#962]
Pharos currently supports calico & weave. Some cases require more exotic configurations , for these it would be nice to have a custom option (bring-your-own-network-provider).

Configuration could be something like this:

```yaml
network:
  provider: custom
  custom:
    path: ./path/to/custom/cni
    options: {}
```
