### ISSUE TITLE
OpenID Connect (oidc)

### ISSUE THREAD

**Issue by sh0rez** [kontena/pharos-cluster#978]
**What would you like to be added**: Support for configuring the OpenID Connect features of `kube-apiserver`

**Why is this needed**: `oidc` is a great way for authentication using Identity Providers (single-sign-on, etc.)
For example, one could leverage existing identity-infrastructure such as GitHub, Google gSuite, etc. to grant access to the cluster. Once the user is removed from the central identity provider, the changes are immediately reflected in the cluster (think of compromised accounts, old team-members, etc.).

See the [official Kubernetes docs](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens) for reference.

After all, there shouldn't be much to be done on `pharos`'s side, as it all comes down to a few [apiserver flags](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server), which are already [supported by kubeadm](https://kubernetes.io/docs/setup/independent/control-plane-flags/#apiserver-flags).

**Example cluster.yml**:

```yaml
hosts:
  - address: 1.1.1.1
    private_interface: eth1
    user: root
    ssh_key_path: ~/.ssh/my_key
    role: master
    container_runtime: cri-o

authentication:
  oidc:
    issuer-url: https://issuer.url
    client-id: kubernetes-cluster
    username-claim: sub
    username-prefix: oidc:
    groups-prefix: oidc:ops
    ca-file: ./root_ca.pem
```
The only challenge that might arise is the handling of `ca-file`, which needs to be an actual file on the system the apiserver is running on. Thus, the local reference must be copied over for example.
