### ISSUE TITLE
Validation error handling cannot handle nested errors

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#998]
**What happened**:

Pharos throws mystic `NoMethodError` if for example addon is missing nested keys.

```
ERROR: NoMethodError : undefined method `join' for {:region=>["is missing"], :bucket=>["is missing"]}:Hash
```

**What you expected to happen**:

Validation error handling should not explode.

**cluster.yml:**

```yaml
addons:
  kontena-backup:
   enabled: true
   cloud_credentials: /path/minio_credentials
   aws:
     s3_force_path_style: true
     s3_url: foo.com/minio/test
```
